apiVersion: v1
kind: Service
metadata:
  name: vibesong-service
spec:
  selector:
    app: vibesong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30081
  type: NodePort
